# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a4c5074430c5c574a07372d986012505089290fa49e741c90132fbd05c674dfda56a84fb7215d49190d0d10ae30abc316c31bcc345df3583133e562a4d1f9178
  BITLY_TOKEN: R_651e0959a753444e891f2e42683e5bed
test:
  secret_key_base: 2d8783cbeac6eaa6c1e2b98497063780be3bf6049f7e54cc7bce676df76b61b88880e5a8204b83bfc071039ea8bebda3444e95840b79567f21f75de87fe89529

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  BITLY_TOKEN: R_651e0959a753444e891f2e42683e5bed
